player_index:
    path:     /
    defaults: { _controller: "LeoGameBundle:Player:index" }
    methods:  GET

player_show:
    path:     /{id}/show
    defaults: { _controller: "LeoGameBundle:Player:show" }
    methods:  GET

player_edit:
    path:     /{id}/edit
    defaults: { _controller: "LeoGameBundle:Player:edit" }
    methods:  [GET, POST]
