<?php

namespace Leo\GameBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\DBAL\LockMode;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerRepository extends EntityRepository {
//
//    public function findAll() {
//        return $this->_em->createQuery("SELECT p, u, pp, pw FROM LeoGameBundle:Player p LEFT JOIN "
//                                . "p.user u LEFT JOIN p.play pp LEFT JOIN p.watch pw")
//                        ->getResult();
//    }
//
//    public function find($id, $lockMode = LockMode::NONE, $lockVersion = null) {
//        return $this->_em->createQuery("SELECT p, pp, pw, u FROM LeoGameBundle:Player p JOIN "
//                                . "p.user u LEFT JOIN p.play pp LEFT JOIN p.watch pw WHERE u.id=?1")
//                        ->setParameter(1, $id)->getSingleResult();
//    }
}
