<?php

namespace Leo\GameBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TypeGameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeGameRepository extends EntityRepository {

}
