<?php

namespace Testing\ConsoleBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository {

    public function findOneByIdJoinedToCategory($id) {
        $query = $this->getEntityManager()
                        ->createQuery(
                                'SELECT p, c FROM AppBundle:Product p
JOIN p.category c
WHERE p.id = :id'
                        )->setParameter('id', $id);
        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

}
