leo_game:
    resource: "@LeoGameBundle/Resources/config/routing.yml"
    prefix:   /game

leo_user:
    resource: "@LeoUserBundle/Resources/config/routing.yml"
    prefix:   /admin

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
