parameters:
    validator.text:
         max: 255
         min: 3
    validator.username:
         max: 35
         min: 3
    validator.mail:
         max: 64
         min: 3
    validator.name:
         max: 35
         min: 3
    validator.password:
         max: 25
         min: 6

services:
    leo_validator.single:
        class: Leo\ValidationBundle\Utils\Validator
#        public: false
#        arguments: ["@service_id", "plain_value", %parameter%]

#    leo_validator.multiply:
#        class: Leo\ValidationBundle\Utils\Validators
#        arguments: ["@leo_validation.single"]
#        calls:
#            - [setMinLength, ["3"]]
#            - [setMaxLength, ["35"]]
#            - [setLetters, ["TRUE"]]
#            - [setNumbers, ["TRUE"]]
#            - [setSpecSymbols, ["TRUE"]]
#            - [setStartLetter, ["TRUE"]]
#            - [setAllSymbols, ["FALSE"]]
