<?php

namespace Leo\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\DBAL\LockMode;

/**
 * RoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleRepository extends EntityRepository {

    public function findAll() {
        return $this->_em->createQuery("SELECT u, r FROM LeoUserBundle:Role r LEFT JOIN "
                        . "r.users u ORDER BY r.id")->getResult();
    }

    public function find($id, $lockMode = LockMode::NONE, $lockVersion = null) {
        return $this->_em->createQuery("SELECT u, r FROM LeoUserBundle:Role r LEFT JOIN r.users u WHERE r.id=?1")
                        ->setParameter(1, $id)->getSingleResult();
    }

}
