<?php

namespace Leo\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Leo\UserBundle\Entity\User;
use \Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository {

//implements UserLoaderInterface {
//
//    public function loadUserByUsername($username) {
////        return $this->findByUsername($username);
//        $result = $this->createQueryBuilder('u')
//                ->where('u.username = :username OR u.email = :email')
//                ->setParameter('username', $username)
//                ->setParameter('email', $username)
//                ->getQuery()
//                ->getOneOrNullResult();
//        var_dump($result);
//        return $result;
//}


    public function findAllWithGames() {
        return $this->_em->createQuery("SELECT u, gp, gw FROM LeoUserBundle:User u LEFT JOIN "
                        . "u.play gp LEFT JOIN u.watch gw ORDER BY u.username")->getResult();
    }

    public function findAllWithPosts() {
        return $this->_em->createQuery("SELECT u, p, c FROM LeoUserBundle:User u LEFT JOIN "
                        . "u.post p LEFT JOIN u.comment c ORDER BY u.username")->getResult();
    }

}
