<?php
namespace Leo\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Leo\UserBundle\Entity\User;
use \Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface;
use Doctrine\DBAL\LockMode;

/**
 * UserRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository implements UserLoaderInterface
{

    public function loadUserByUsername($username)
    {
//        return $this->findByUsername($username);
        $result = $this->createQueryBuilder('u')
            ->where('u.username = :username OR u.email = :email')
            ->setParameter('username', $username)
            ->setParameter('email', $username)
            ->getQuery()
            ->getOneOrNullResult();
//        var_dump($result);
        return $result;
    }

    public function findAll()
    {
        return $this->_em->createQuery("SELECT u, r FROM LeoUserBundle:User u JOIN "
            . "u.role r ORDER BY u.id")->getResult();
    }

//    public function find($id, $lockMode = LockMode::NONE, $lockVersion = null) {
//        return $this->_em->createQuery("SELECT u, r FROM LeoUserBundle:User u JOIN u.role r WHERE u.id=?1")
//                        ->setParameter(1, $id)->getOneOrNullResult();
//    }
    public function findAllWithGames()
    {
        return $this->_em->createQuery("SELECT u, gp, gw FROM LeoUserBundle:User u LEFT JOIN "
            . "u.play gp LEFT JOIN u.watch gw ORDER BY u.id")->getResult();
    }

    public function findAllWithPosts()
    {
        return $this->_em->createQuery("SELECT u, p, c FROM LeoUserBundle:User u LEFT JOIN "
            . "u.post p LEFT JOIN u.comment c ORDER BY u.id")->getResult();
    }

}
