<?php
namespace Leo\BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\DBAL\LockMode;

/**
 * CommentRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{

    public function findAll()
    {
        return $this->_em->createQuery("SELECT c, a, p FROM LeoBlogBundle:Comment c LEFT JOIN "
            . "c.author a LEFT JOIN c.post p ORDER BY c.id")->getResult();
    }

    public function find($id, $lockMode = LockMode::NONE, $lockVersion = NULL)
    {
        return $this->_em->createQuery("SELECT c, a, p FROM LeoBlogBundle:Comment c "
            . "JOIN c.author a JOIN c.post p WHERE c.id=?1")
            ->setParameter(1, $id)->getSingleResult();
    }

}
