<?php
namespace Leo\BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\DBAL\LockMode;

/**
 * PostRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{

    public function findAll()
    {
        return $this->_em->createQuery("SELECT a, p, c, ac FROM LeoBlogBundle:Post p LEFT JOIN "
            . "p.author a LEFT JOIN p.comments c LEFT JOIN c.author ac")->getResult();
    }

    public function find($id, $lockMode = LockMode::NONE, $lockVersion = NULL)
    {
        return $this->_em->createQuery("SELECT a, p, c FROM LeoBlogBundle:Post p LEFT JOIN p.author a "
            . "LEFT JOIN p.comments c WHERE p.id=:param")
            ->setParameter('param', $id)->getSingleResult();
    }

}
